# Generated by Django 5.0 on 2025-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
