# Generated by Django 5.0 on 2025-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_radius_km',
            field=models.PositiveIntegerField(blank=True, help_text='Preferred commute radius (km)', null=True),
        ),
    ]
