# Generated by Django 5.0 on 2025-11-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_jobseekerprofile_city_jobseekerprofile_home_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='home_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
