# Generated by Django 5.0 on 2025-10-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_jobseekerprofile_apartment_jobseekerprofile_city_and_more'),
        ('profiles', '0005_delete_project'),
    ]

    operations = [
    ]
