# Generated by Django 5.0 on 2025-10-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_20251021_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='apartment',
        ),
    ]
