# Generated by Django 5.0 on 2025-11-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_jobseekerprofile_home_address'),
        ('profiles', '0007_rename_street_jobseekerprofile_address_and_more'),
    ]

    operations = [
    ]
