# Generated by Django 5.0 on 2025-11-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_street_jobseekerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for recruiters', max_length=254, null=True),
        ),
    ]
