# Generated by Django 5.0 on 2025-11-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_merge_20251116_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='home_lat',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='home_lng',
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
