# Generated by Django 5.0 on 2025-11-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_jobseekerprofile_email'),
        ('profiles', '0009_remove_jobseekerprofile_home_address_and_more'),
    ]

    operations = [
    ]
