# Generated by Django 5.0 on 2025-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skills', models.TextField(help_text='List required skills, separated by commas')),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('IN', 'Internship'), ('CT', 'Contractor')], max_length=2)),
                ('visa_sponsorship', models.CharField(choices=[('YES', 'Sponsorship Available'), ('NO', 'No Sponsorship')], default='NO', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
