# Generated by Django 5.0 on 2025-09-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote_type',
            field=models.CharField(choices=[('ON', 'On-site'), ('RE', 'Remote'), ('HY', 'Hybrid')], default='ON', max_length=2),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['remote_type'], name='jobs_job_remote__161327_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
    ]
