# Generated by Django 5.0 on 2025-09-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
        ('jobs', '0003_job_recruiter'),
    ]

    operations = [
    ]
