# Generated by Django 5.0 on 2025-09-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_options_alter_job_skills_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
