# Generated by Django 5.0 on 2025-09-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_merge_0003_application_0003_job_recruiter'),
        ('jobs', '0005_alter_application_options_and_more'),
    ]

    operations = [
    ]
