# Generated by Django 5.0 on 2025-10-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_lat_job_lng'),
        ('recruiters', '0002_remove_recruiter_company_remove_recruiter_phone_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_locatio_8b2f8c_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='apartment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['city'], name='jobs_job_city_e9517f_idx'),
        ),
    ]
