# Generated by Django 5.0 on 2025-10-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_jobs_job_locatio_8b2f8c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='job',
            name='street',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, help_text='Full address or office location', max_length=255),
        ),
    ]
