# Generated by Django 5.0 on 2025-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_apartment_remove_job_street_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, help_text='Type office location or adjust pin on map', max_length=255),
        ),
    ]
