# Generated by Django 5.0 on 2025-09-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='phone',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
