# Generated by Django 5.2.6 on 2025-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_remove_recruiter_company_remove_recruiter_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='is_public',
            field=models.BooleanField(default=False, help_text="Allow job seekers/recruiters to view this recruiter's profile and contact details"),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
