# Generated by Django 5.0 on 2025-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_recruiter_contact_email_recruiter_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow job seekers/recruiters to view your profile and contact details'),
        ),
    ]
